sonar.projectKey=hearst-connect-defi
sonar.projectName=Hearst Connect DeFi
sonar.host.url=http://100.88.191.49:9010

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/.next/**

sonar.sourceEncoding=UTF-8
