// Generates .design-sync/ds-entry.tsx (the bundle barrel → window.HearstDS)
// and prints the componentSrcMap for config.json. Run from repo root:
//   node .design-sync/gen-entry.mjs
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

// name -> source file (relative to src/components/ui)
const FILE = {
  ApyRange: 'apy-range',
  Badge: 'badge',
  Button: 'button',
  Card: 'card',
  ChartTimeSelector: 'chart-time-selector',
  Checkbox: 'checkbox',
  ChoiceCard: 'choice-card',
  ConfirmDialog: 'confirm-dialog',
  DashboardPanelHeader: 'dashboard-panel-header',
  DataRow: 'nested-panel',
  EmptySurface: 'empty-surface',
  Metric: 'metric',
  MetricGrid: 'nested-panel',
  Modal: 'modal',
  NestedPanel: 'nested-panel',
  PanelStatus: 'panel-status',
  PresetPicker: 'preset-picker',
  Progress: 'progress',
  ProvenanceBadge: 'provenance-badge',
  Ptai: 'ptai',
  ProofRow: 'nested-panel',
  SegmentedControl: 'segmented-control',
  Skeleton: 'skeleton',
  Tooltip: 'tooltip',
  WizardStepProgress: 'wizard-step-progress',
};

// Compositional siblings exported on the global (for previews) but NOT standalone cards.
const SIBLINGS = {
  card: ['CardHeader', 'CardTitle'],
  'choice-card': ['ChoiceGroup'],
  'panel-status': ['PanelStatusSection', 'PanelStatusAccent'],
  skeleton: ['SkeletonCard'],
  'nested-panel': ['LegalMetadataRow'],
};

// Build per-file export list: cards + siblings, grouped by file.
const byFile = {};
for (const [name, file] of Object.entries(FILE)) {
  (byFile[file] ??= new Set()).add(name);
}
for (const [file, names] of Object.entries(SIBLINGS)) {
  for (const n of names) (byFile[file] ??= new Set()).add(n);
}

const lines = [
  '// AUTO-GENERATED by .design-sync/gen-entry.mjs — the design-sync bundle barrel.',
  '// Re-exports the curated Hearst Connect ui/ primitives onto window.HearstDS.',
  '// Edit gen-entry.mjs (not this file) and re-run to regenerate.',
];
for (const file of Object.keys(byFile).sort()) {
  const names = [...byFile[file]].sort();
  lines.push(`export { ${names.join(', ')} } from "../src/components/ui/${file}";`);
}
// Preview frame (cfg.provider) — applies the DS dark surface behind every card.
lines.push('export { __DsFrame } from "./ds-frame";');
const entry = lines.join('\n') + '\n';
writeFileSync(join(process.cwd(), '.design-sync', 'ds-entry.tsx'), entry);

const srcMap = {};
for (const [name, file] of Object.entries(FILE)) {
  srcMap[name] = `src/components/ui/${file}.tsx`;
}
console.log('=== ds-entry.tsx written ===');
console.log(entry);
console.log('=== componentSrcMap (' + Object.keys(srcMap).length + ' components) ===');
console.log(JSON.stringify(srcMap, null, 2));
