import { ShieldCheck, KeyRound, LifeBuoy } from "lucide-react";

import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { Card } from "@/components/ui/card";
import { DashboardPanelHeader } from "@/components/ui/dashboard-panel-header";
import { requireAdmin } from "@/lib/auth/require-admin";
import { isTotpEnabled } from "@/lib/auth/totp";

import { TotpEnrolmentClient } from "./TotpEnrolmentClient";

import "../admin-proof.css";

export const metadata = {
  title: "Account security — Hearst Connect",
};

export const dynamic = "force-dynamic";

const PROTECTIONS = [
  {
    icon: ShieldCheck,
    title: "Why it matters",
    detail:
      "Admin accounts draft governance, outreach and product actions. A second factor blocks access even if a password leaks.",
  },
  {
    icon: KeyRound,
    title: "Offline codes",
    detail:
      "TOTP codes are generated by your authenticator app — never sent by SMS or email, and never stored on our side.",
  },
  {
    icon: LifeBuoy,
    title: "Keep a backup",
    detail:
      "Save the setup key or back up your authenticator. Losing it requires an operator reset to regain access.",
  },
] as const;

export default async function AdminSecurityPage() {
  const { userId } = await requireAdmin();
  const totpEnabled = await isTotpEnabled(userId);

  return (
    <div className="admin-doc-stack admin-doc-stack--roomy">
      <AdminPageHeader
        titleLead="Security"
        titleAccent="Center"
        contextLabel="Account Security"
      />

      <div className="security-grid">
        <Card>
          <DashboardPanelHeader title="Two-factor sign-in (TOTP)" tone="quiet" />
          <p className="body-xs ct-text-muted security-totp-lead">
            Use an authenticator app (Google Authenticator, Authy, 1Password) to
            generate a time-based code at login. Required once enrolled.
          </p>
          <TotpEnrolmentClient initialEnabled={totpEnabled} />
        </Card>

        <Card material="flat">
          <DashboardPanelHeader title="Account protection" tone="quiet" />
          <ul className="security-guidance">
            {PROTECTIONS.map((item) => (
              <li key={item.title} className="security-guidance__item">
                <span className="security-guidance__icon" aria-hidden="true">
                  <item.icon className="ct-icon-sm ct-text-muted" />
                </span>
                <span className="admin-doc-stack admin-doc-stack--tight">
                  <span className="body-sm ct-text-primary">{item.title}</span>
                  <span className="body-xs ct-text-muted">{item.detail}</span>
                </span>
              </li>
            ))}
          </ul>
        </Card>
      </div>
    </div>
  );
}
