import { ShieldCheck, KeyRound, LifeBuoy } from "lucide-react";

import { AdminPageShell, AdminSectionCard } from "@/components/admin/admin-page-shell";
import { requireAdmin } from "@/lib/auth/require-admin";
import { isTotpEnabled } from "@/lib/auth/totp";

import { TotpEnrolmentClient } from "./TotpEnrolmentClient";

import "../admin-proof.css";

export const metadata = {
  title: "Account security — Hearst Connect",
};

export const dynamic = "force-dynamic";

const PROTECTIONS = [
  {
    icon: ShieldCheck,
    title: "Why it matters",
    detail:
      "Admin accounts draft governance, outreach and product actions. A second factor blocks access even if a password leaks.",
  },
  {
    icon: KeyRound,
    title: "Offline codes",
    detail:
      "TOTP codes are generated by your authenticator app — never sent by SMS or email, and never stored on our side.",
  },
  {
    icon: LifeBuoy,
    title: "Keep a backup",
    detail:
      "Save the setup key or back up your authenticator. Losing it requires an operator reset to regain access.",
  },
] as const;

export default async function AdminSecurityPage() {
  const { userId } = await requireAdmin();
  const totpEnabled = await isTotpEnabled(userId);

  return (
    <AdminPageShell
      titleLead="Security"
      titleAccent="Center"
      contextLabel="Account Security"
    >
      {/* ANTI-TROU : enrolment (interactif, hauteur variable) vs guidance (liste
          de 3 lignes) sont des volumes très inégaux. Tracks asymétriques avec
          items-start au lieu d'un grid-cols-2 rigide qui creuserait un trou sous
          la colonne courte. */}
      <div className="grid grid-cols-1 items-start gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <AdminSectionCard
          title="Two-factor sign-in (TOTP)"
          subtitle="Required once enrolled"
          ariaLabel="Two-factor sign-in"
        >
          <div className="flex min-w-0 flex-col gap-4 p-5">
            <p className="ct-metric-caption leading-relaxed">
              Use an authenticator app (Google Authenticator, Authy, 1Password)
              to generate a time-based code at login. Required once enrolled.
            </p>
            <TotpEnrolmentClient initialEnabled={totpEnabled} />
          </div>
        </AdminSectionCard>

        <AdminSectionCard
          title="Account protection"
          subtitle="Guidance & recovery"
          ariaLabel="Account protection"
        >
          <ul className="flex flex-col">
            {PROTECTIONS.map((item) => (
              <li
                key={item.title}
                className="flex items-start gap-4 border-b border-[var(--ct-border-soft)] p-5 last:border-b-0"
              >
                <span
                  className="flex size-9 shrink-0 items-center justify-center rounded-lg border border-[var(--ct-border)] bg-surface-inset"
                  aria-hidden="true"
                >
                  <item.icon className="size-4 text-[var(--ct-accent)]" />
                </span>
                <span className="flex min-w-0 flex-col gap-1.5">
                  <span className="ct-metric-value">{item.title}</span>
                  <span className="ct-metric-caption leading-relaxed">
                    {item.detail}
                  </span>
                </span>
              </li>
            ))}
          </ul>
        </AdminSectionCard>
      </div>
    </AdminPageShell>
  );
}
