import { ShieldCheck, KeyRound, LifeBuoy } from "lucide-react";

import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { BentoHeader, BentoPanel } from "@/components/ui/bento";
import { requireAdmin } from "@/lib/auth/require-admin";
import { isTotpEnabled } from "@/lib/auth/totp";

import { TotpEnrolmentClient } from "./TotpEnrolmentClient";

import "../admin-proof.css";

export const metadata = {
  title: "Account security — Hearst Connect",
};

export const dynamic = "force-dynamic";

const PROTECTIONS = [
  {
    icon: ShieldCheck,
    title: "Why it matters",
    detail:
      "Admin accounts draft governance, outreach and product actions. A second factor blocks access even if a password leaks.",
  },
  {
    icon: KeyRound,
    title: "Offline codes",
    detail:
      "TOTP codes are generated by your authenticator app — never sent by SMS or email, and never stored on our side.",
  },
  {
    icon: LifeBuoy,
    title: "Keep a backup",
    detail:
      "Save the setup key or back up your authenticator. Losing it requires an operator reset to regain access.",
  },
] as const;

export default async function AdminSecurityPage() {
  const { userId } = await requireAdmin();
  const totpEnabled = await isTotpEnabled(userId);

  return (
    <div className="dark flex flex-col rounded-2xl border border-[var(--ct-border)] bg-surface-page [--gutter:theme(spacing.8)] mb-8">
      <div className="p-5 lg:p-6 flex flex-col gap-y-5">
        <AdminPageHeader
          titleLead="Security"
          titleAccent="Center"
          contextLabel="Account Security"
        />

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          <BentoPanel>
            <BentoHeader
              title="Two-factor sign-in (TOTP)"
              subtitle="Required once enrolled"
            />
            <div className="flex flex-col gap-4 p-5">
              <p className="ct-metric-caption leading-relaxed">
                Use an authenticator app (Google Authenticator, Authy, 1Password)
                to generate a time-based code at login. Required once enrolled.
              </p>
              <TotpEnrolmentClient initialEnabled={totpEnabled} />
            </div>
          </BentoPanel>

          <BentoPanel>
            <BentoHeader
              title="Account protection"
              subtitle="Guidance & recovery"
            />
            <ul className="flex flex-col">
              {PROTECTIONS.map((item) => (
                <li
                  key={item.title}
                  className="flex items-start gap-4 border-b border-[var(--ct-border-soft)] p-5 last:border-b-0"
                >
                  <span
                    className="flex size-9 shrink-0 items-center justify-center rounded-lg border border-[var(--ct-border)] bg-surface-inset"
                    aria-hidden="true"
                  >
                    <item.icon className="size-4 text-[var(--ct-accent)]" />
                  </span>
                  <span className="flex min-w-0 flex-col gap-1.5">
                    <span className="ct-metric-value">
                      {item.title}
                    </span>
                    <span className="ct-metric-caption leading-relaxed">
                      {item.detail}
                    </span>
                  </span>
                </li>
              ))}
            </ul>
          </BentoPanel>
        </div>
      </div>
    </div>
  );
}
