import { KeyRound, LifeBuoy, ShieldCheck, type LucideIcon } from "lucide-react";

import { TotpEnrolmentClient } from "@/app/admin/security/TotpEnrolmentClient";
import { PageHeader, PageLayout, Panel, Section } from "@/views/_shared/layout";

const PROTECTIONS: ReadonlyArray<{
  icon: LucideIcon;
  title: string;
  detail: string;
}> = [
  {
    icon: ShieldCheck,
    title: "Why it matters",
    detail:
      "Admin accounts draft governance, outreach and product actions. A second factor blocks access even if a password leaks.",
  },
  {
    icon: KeyRound,
    title: "Offline codes",
    detail:
      "TOTP codes are generated by your authenticator app — never sent by SMS or email, and never stored on our side.",
  },
  {
    icon: LifeBuoy,
    title: "Keep a backup",
    detail:
      "Save the setup key or back up your authenticator. Losing it requires an operator reset to regain access.",
  },
];

export function AdminSecurityView({ totpEnabled }: { totpEnabled: boolean }) {
  return (
    <PageLayout>
      <PageHeader
        eyebrow="Account"
        title="Security center"
        description="Protect admin access with time-based one-time passwords."
      />

      <div className="grid grid-cols-1 items-start gap-5 lg:grid-cols-2">
        <Section title="Two-factor sign-in (TOTP)">
          <Panel
            title="Authenticator app"
            description="Required once enrolled."
          >
            <div className="flex min-w-0 flex-col gap-4 p-5">
              <p className="text-sm leading-relaxed text-[var(--ct-text-muted)]">
                Use an authenticator app (Google Authenticator, Authy, 1Password)
                to generate a time-based code at login.
              </p>
              <TotpEnrolmentClient initialEnabled={totpEnabled} />
            </div>
          </Panel>
        </Section>

        <Section title="Account protection">
          <Panel title="Guidance & recovery">
            <ul className="flex flex-col">
              {PROTECTIONS.map((item) => (
                <li
                  key={item.title}
                  className="flex items-start gap-4 border-b border-[var(--ct-border)] p-5 last:border-b-0"
                >
                  <span
                    className="flex size-9 shrink-0 items-center justify-center rounded-lg border border-[var(--ct-border)] bg-surface-inset"
                    aria-hidden="true"
                  >
                    <item.icon className="size-4 text-accent" />
                  </span>
                  <span className="flex min-w-0 flex-col gap-1.5">
                    <span className="text-sm font-semibold text-[var(--ct-text-strong)]">
                      {item.title}
                    </span>
                    <span className="text-sm leading-relaxed text-[var(--ct-text-muted)]">
                      {item.detail}
                    </span>
                  </span>
                </li>
              ))}
            </ul>
          </Panel>
        </Section>
      </div>
    </PageLayout>
  );
}
