#!/usr/bin/env node
/**
 * scripts/component-index.mjs — generates docs/COMPONENT_INDEX.md.
 *
 * The index is the "always reuse the existing component" enforcement: a fresh,
 * grep-able inventory of every component (name → path → exported symbols →
 * how many other files reference it). An agent MUST consult it before creating
 * a component, so it can reuse an existing one (or refactor it in place) rather
 * than fork a duplicate. The pre-commit hook regenerates it so it never goes
 * stale; with `--stage` it re-stages the file when (and only when) it changed.
 *
 * This is generated — never hand-edit docs/COMPONENT_INDEX.md.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const COMPONENTS_DIR = join(ROOT, "src", "components");
const SRC_DIR = join(ROOT, "src");
const OUT = join(ROOT, "docs", "COMPONENT_INDEX.md");

// Intentionally built-but-unwired components (Adrien decision 2026-06-10) —
// flagged "unwired", NOT "orphan", and never to be deleted by a cleanup pass.
const UNWIRED = new Set([
  "global-search",
  "shortcuts-overlay",
  "notifications-bell",
  "saved-views-picker",
  "chart-time-selector",
]);

function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (name === "__tests__" || name === "node_modules") continue;
      walk(full, acc);
    } else if (/\.tsx$/.test(name) && !/\.test\.tsx$/.test(name)) {
      acc.push(full);
    }
  }
  return acc;
}

function exportedNames(src) {
  const names = new Set();
  const patterns = [
    /export\s+(?:default\s+)?function\s+([A-Z]\w+)/g,
    /export\s+const\s+([A-Z]\w+)\s*[:=]/g,
    /export\s+(?:abstract\s+)?class\s+([A-Z]\w+)/g,
  ];
  for (const re of patterns) {
    let m;
    while ((m = re.exec(src))) names.add(m[1]);
  }
  const named = src.match(/export\s+\{([^}]+)\}/g) ?? [];
  for (const block of named) {
    for (const part of block.replace(/export\s+\{|\}/g, "").split(",")) {
      const id = part.trim().split(/\s+as\s+/)[0]?.trim();
      if (id && /^[A-Z]\w+$/.test(id)) names.add(id);
    }
  }
  return [...names];
}

function build() {
  const files = walk(COMPONENTS_DIR);
  // Load the whole src corpus once for reference counting.
  const corpus = walk2(SRC_DIR).map((f) => ({ f, text: readFileSync(f, "utf8") }));

  const rows = files.map((full) => {
    const rel = relative(ROOT, full);
    const base = rel.split("/").pop().replace(/\.tsx$/, "");
    const src = readFileSync(full, "utf8");
    const exports = exportedNames(src);
    // Reference count: other src files that import from this file's path
    // (by basename, alias, or relative) OR mention a primary export name.
    const needle = base;
    let refs = 0;
    for (const { f, text } of corpus) {
      if (f === full) continue;
      if (/\.test\.tsx?$/.test(f)) continue;
      if (text.includes(`/${needle}"`) || text.includes(`/${needle}'`)) {
        refs++;
        continue;
      }
      if (exports.length && exports.some((n) => new RegExp(`\\b${n}\\b`).test(text))) {
        refs++;
      }
    }
    const unwired = UNWIRED.has(base);
    const status = unwired ? "unwired" : refs === 0 ? "ORPHAN?" : "ok";
    return { rel, base, exports, refs, status };
  });

  rows.sort((a, b) => a.rel.localeCompare(b.rel));

  const orphans = rows.filter((r) => r.status === "ORPHAN?");
  const unwired = rows.filter((r) => r.status === "unwired");

  let md = `# COMPONENT_INDEX (generated — do not hand-edit)\n\n`;
  md += `> Regenerated by \`pnpm quality:index\` and the pre-commit hook. **Before creating any\n`;
  md += `> component, search this index.** If it already exists, REUSE it. If it exists but is in\n`;
  md += `> bad shape, refactor it IN PLACE and delete the old version — never fork a second copy.\n\n`;
  md += `**${rows.length} components** · ${orphans.length} possible orphans · ${unwired.length} intentionally unwired.\n\n`;

  if (orphans.length) {
    md += `## ⚠️ Possible orphans (0 references — verify before keeping)\n\n`;
    for (const r of orphans) md += `- \`${r.rel}\` — ${r.exports.join(", ") || "(no named export)"}\n`;
    md += `\n`;
  }
  if (unwired.length) {
    md += `## Intentionally unwired (built, tested, branch-later — do NOT delete)\n\n`;
    for (const r of unwired) md += `- \`${r.rel}\` — ${r.exports.join(", ")}\n`;
    md += `\n`;
  }

  md += `## All components\n\n`;
  md += `| Component file | Exports | Refs |\n|---|---|---|\n`;
  for (const r of rows) {
    const flag = r.status === "ORPHAN?" ? " ⚠️" : r.status === "unwired" ? " 🔌" : "";
    md += `| \`${r.rel}\`${flag} | ${r.exports.join(", ") || "—"} | ${r.refs} |\n`;
  }
  md += `\nLegend: ⚠️ possible orphan · 🔌 intentionally unwired.\n`;
  return md;
}

// second walker for .ts + .tsx corpus
function walk2(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (name === "node_modules") continue;
      walk2(full, acc);
    } else if (/\.tsx?$/.test(name)) {
      acc.push(full);
    }
  }
  return acc;
}

const next = build();
let prev = "";
try {
  prev = readFileSync(OUT, "utf8");
} catch {
  /* first run */
}
if (next !== prev) {
  writeFileSync(OUT, next);
  console.log("component-index: docs/COMPONENT_INDEX.md updated");
  if (process.argv.includes("--stage")) {
    try {
      execSync(`git add ${JSON.stringify(relative(ROOT, OUT))}`, { cwd: ROOT });
    } catch {
      /* not a git context / nothing to stage */
    }
  }
} else {
  console.log("component-index: up to date");
}
